#!/usr/bin/env bash
# Shell fonts for the MagikOS Quickshell bar.
#
# WHY THIS FILE EXISTS
#
# The bar does not name a font family for its icons. `Style.qml` sets
# `fontFamily: "monospace"` (shell/Commons/Style.qml:227) and every icon
# codepoint in the tree is drawn with that family. Upstream Arch/CachyOS
# ships Nerd Fonts, so "monospace" happens to resolve to one there.
#
# On a stock Void box `fc-match monospace` resolves to DejaVu Sans Mono, which
# has no private-use-area glyphs. Result: every bar icon, tray icon and menu
# glyph is a tofu box. Installing a Nerd Font is therefore necessary but NOT
# sufficient -- it also has to win the "monospace" match, which is what
# `install_font_aliases` does.
#
# WHY NOT `nerd-fonts-ttf`
#
# Void's `nerd-fonts-ttf` is an every-family aggregator: 1517 MB to download and
# 7447 MB installed, to obtain the one family we use. That is also why an
# earlier installer "failed to download the fonts" -- it was trying to pull 1.5
# GB inside a package transaction that had already failed for another reason.
# Fetching the single JetBrainsMono Nerd Font zip from upstream releases is
# ~128 MB and needs nothing beyond curl + python3, both bootstrap tools.

NERD_FONT_FAMILY="${NERD_FONT_FAMILY:-JetBrainsMono Nerd Font}"
NERD_FONT_VERSION="${NERD_FONT_VERSION:-3.5.1}"
NERD_FONT_ZIP="JetBrainsMono.zip"
FONT_DIR="${FONT_DIR:-$HOME/.local/share/fonts/magikos-nerd}"

nerd_font_url() {
    printf 'https://github.com/ryanoasis/nerd-fonts/releases/download/v%s/%s' \
        "$NERD_FONT_VERSION" "$NERD_FONT_ZIP"
}

# Is the font already present and visible to fontconfig?
nerd_font_present() {
    have fc-match || return 1
    fc-match "$NERD_FONT_FAMILY" 2>/dev/null |
        awk -v f="$NERD_FONT_FAMILY" 'NR==1 && index($0, f) { found=1 } END { exit !found }'
}

# Prefer the Nerd Font for `monospace` (the bar's icon family) and for the
# families upstream maps icon themes onto. This is the step that actually makes
# glyphs appear; see the header note.
install_font_aliases() {
    local conf_dir="${XDG_CONFIG_HOME:-$HOME/.config}/fontconfig/conf.d"
    local conf="$conf_dir/99-magikos-nerd.conf"

    if ((DRY_RUN == 1)); then
        _c mkdir -p "$conf_dir"
        _c cp "$FONT_DIR/../magikos-nerd-fontconfig.xml" "$conf"
        return 0
    fi

    mkdir -p "$conf_dir" || { err "cannot write $conf_dir"; return 1; }

    cat > "$conf" <<EOF
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<!-- Generated by MagikVoidOS install.sh. Makes the Quickshell bar's icon
     glyphs render: the bar draws Nerd Font codepoints with the default
     "monospace" family, so the Nerd Font has to win that match. -->
<fontconfig>
  <match target="pattern">
    <test qual="any" name="family"><string>monospace</string></test>
    <edit name="family" mode="assign" binding="strong">
      <string>$NERD_FONT_FAMILY</string>
    </edit>
  </match>
  <match target="pattern">
    <test qual="any" name="family"><string>MagikOS Icons</string></test>
    <edit name="family" mode="assign" binding="strong">
      <string>$NERD_FONT_FAMILY</string>
    </edit>
  </match>
</fontconfig>
EOF
    ok "font alias: monospace -> $NERD_FONT_FAMILY"
}

# Download (once, cached) and install the Nerd Font, then refresh the cache.
install_shell_fonts() {
    if nerd_font_present; then
        ok "shell font present ($NERD_FONT_FAMILY)"
        install_font_aliases
        return 0
    fi

    require_cmd curl     || return 1
    require_cmd python3  || return 1

    local cache="${TMPDIR:-/tmp}/magikos-void-fonts"
    local zip="$cache/v$NERD_FONT_VERSION/$NERD_FONT_ZIP"
    local url
    url="$(nerd_font_url)"

    if [[ ! -s $zip ]]; then
        log "Fetching $NERD_FONT_FAMILY v$NERD_FONT_VERSION (~128 MB)"
        if ((DRY_RUN == 1)); then
            _c mkdir -p "$(dirname "$zip")"
            _c curl -fL --retry 3 -o "$zip" "$url"
            return 0
        fi
        mkdir -p "$(dirname "$zip")" || return 1
        # -f so an HTML error page is not saved as a "font"; --retry for flaky
        # mirrors. A truncated zip is caught by the extraction step below.
        if ! curl -fL --retry 3 --retry-delay 2 -o "$zip" "$url"; then
            err "font download failed: $url"
            err "retry later, or drop a $NERD_FONT_ZIP at $zip"
            return 1
        fi
    else
        log "Using cached $NERD_FONT_ZIP"
    fi

    if ((DRY_RUN == 1)); then
        _c mkdir -p "$FONT_DIR"
        _c fc-cache -f "$FONT_DIR"
        return 0
    fi

    mkdir -p "$FONT_DIR" || return 1
    # Unpack with python3: Void has no hard dependency on unzip, and python3 is
    # already a bootstrap tool. Select font files only; the zip also carries
    # README/LICENSE and per-variant directories that are just noise.
    if ! python3 - "$zip" "$FONT_DIR" <<'PY'
import os, sys, zipfile

zpkg, dest = sys.argv[1], sys.argv[2]
n = 0
try:
    with zipfile.ZipFile(zpkg) as z:
        for info in z.infolist():
            if info.is_dir():
                continue
            base = os.path.basename(info.filename)
            if not base.lower().endswith((".ttf", ".otf")):
                continue
            # Guard against zip-slip style absolute/traversal names.
            with z.open(info) as src, open(os.path.join(dest, base), "wb") as out:
                out.write(src.read())
            n += 1
except zipfile.BadZipFile:
    sys.stderr.write("not a valid zip (truncated download?)\n")
    sys.exit(1)
print(n)
PY
    then
        err "could not unpack $NERD_FONT_ZIP"
        rm -f "$zip"
        return 1
    fi

    if ! ls "$FONT_DIR"/*.ttf "$FONT_DIR"/*.otf >/dev/null 2>&1; then
        err "no font files extracted into $FONT_DIR"
        return 1
    fi

    _c fc-cache -f "$FONT_DIR" || warn "fc-cache failed; restart the session"
    ok "installed $(ls "$FONT_DIR" | wc -l) font files into $FONT_DIR"

    if ! nerd_font_present; then
        warn "font files are in place but fontconfig does not see $NERD_FONT_FAMILY"
        return 1
    fi
    ok "shell font registered ($NERD_FONT_FAMILY)"

    install_font_aliases
    fc-match monospace >/dev/null 2>&1
    if fc-match monospace 2>/dev/null | head -1 | awk -v f="$NERD_FONT_FAMILY" 'index($0, f) { f=1 } END { exit !f }'; then
        ok "monospace now resolves to the Nerd Font (bar glyphs will render)"
    else
        warn "monospace still resolves elsewhere: $(fc-match monospace 2>/dev/null | head -1)"
        warn "log out and back in so Qt reloads the font cache"
    fi
}